### ISSUE TITLE
jayone 과제 5/22~5/28

### ISSUE THREAD

**Issue by zeroam** [TryOC-1/dev-study#37]
### 웹
- [x] Flask 웹 서비스 구현하기
  - [x] DB 연동(ORM)
  - [x] 프론트엔드 페이지 구현
  - [x] 백엔드 API 구현
  - [x] heroku 배포
  - [x] redis 연동
  - Link - [flask-by-example](https://github.com/realpython/flask-by-example)

### built-in library
- [x] [abc — Abstract Base Classes](https://pymotw.com/3/abc/)
- [x] [Counter](https://pymotw.com/2/collections/counter.html)

**Comment by BoKyeong-Kim** [comment]
https://courses.analyticsvidhya.com/courses/tableau-for-beginners
ㄴ 태블로 참고 자료

**Comment by zeroam** [comment]
> https://courses.analyticsvidhya.com/courses/tableau-for-beginners
> ㄴ 태블로 참고 자료

@BoKyeong-Kim 감사합니다~! 참고할께요~~
